---
title: "Water and Drought Plans"
author: "Rachel McKane"
date: "August 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls()) #clears variables in global environment :-)
#dev.off() #clears plots in history

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = "/Users/rachelmckane/Desktop/Plans")

getwd()
```


```{r}
library("tidyverse") #includes dplyr, ggplot2, tidyr, purr, readr, and tibble
library("broom") #has the tidy fn to convert non-tidy objects into tidy objects
library("SnowballC")
library("stringr") #has str_extract fn to avoid some of the strange utf-8 text encodings
library("tm") #has a lot of text cleaning fns, like remove numbers and punctuation; incl. NLP and slam
library("tidytext") #has unnest_tokens fn; includes SnowballC; #has tidy fn to convert topics into tidy format
library("topicmodels")
library("wordcloud")
library("quanteda")
library("pdftools")
```


###Reading in the Water Plans 


```{r}
read <- readPDF(control = list(text = "-layout")) #define engine
files <- list.files(path = "/Users/rachelmckane/Desktop/Plans2/", pattern = "pdf$")
files_path <- paste("/Users/rachelmckane/Desktop/Plans2/",files,sep="")
WaterPlansRaw <- VCorpus(URISource(files_path), 
                            readerControl = list(reader = read))


class(WaterPlansRaw) 

saveRDS(WaterPlansRaw, file = "/Users/rachelmckane/Desktop/WaterPlansRaw.Rds")
```

###Clean up the VCorpus (Water Plans)

This is the code we use to clean up all of the PDF Files. We should think about the exact stopwords we want to take out. 

```{r}
#define all stop words (including specific ones we add, such as state names)
stpwrds <- tm::stopwords("SMART") #list of stopwords in the tm pkg for the SMART option
addwords <- c( "state", "water","plan", "colorado") 
states <- read.csv("/Users/rachelmckane/Desktop/State_List.csv", stringsAsFactors = FALSE)
all_stopwords <- c(stpwrds,addwords,states[['State']],states[['State_Abbreviation']]) #merge the two lists
all_stopwords <- tolower(all_stopwords) #make all state names/abbrevs lowercase
rm(stpwrds,addwords,states) 

  
  
  (f_weirdos <- content_transformer(function(x, pattern) gsub(pattern, "", x)))

#now do some special corpus cleaning...order of functions matters!
WaterPlanProcessed <- WaterPlans_text %>%
  tm_map(f_weirdos,"[^[:alnum:] ]") %>% #gets rid of form feed (/f) and euro symbol, but not a accents
  tm_map(f_weirdos,"â") %>% #remove accents
  tm_map(content_transformer(tolower)) %>% #Switch to lower case
  tm_map(removeWords, all_stopwords) %>% #remove stopwords; want to remove stopwords 1st because they contain punctuation
  tm_map(removePunctuation) %>% #Remove punctuation marks 
  tm_map(removeNumbers) %>% #Remove numbers
  tm_map(stripWhitespace) #Remove white space 
  

saveRDS(WaterPlanProcessed, file = "/Users/rachelmckane/Desktop/WaterPlanProcessed.Rds")

```




###Reading in the Drought Plans 

```{r}

read <- readPDF(control = list(text = "-layout")) #define engine
files <- list.files(path = "/Users/rachelmckane/Desktop/Plans2/", pattern = "pdf$")
files_path <- paste("/Users/rachelmckane/Desktop/Plans2/",files,sep="")
DroughtPlanRaw<- VCorpus(URISource(files_path), 
                            readerControl = list(reader = read))


class(DroughtPlanRaw) 
```

###Clean up the VCorpus (Drought Plans)

```{r}
#define all stop words (including specific ones we add, such as state names)
stpwrds <- tm::stopwords("SMART") #list of stopwords in the tm pkg for the SMART option
addwords <- c( "state", "water","plan", "colorado", "drought") 
states <- read.csv("/Users/rachelmckane/Desktop/State_List.csv", stringsAsFactors = FALSE)
all_stopwords <- c(stpwrds,addwords,states[['State']],states[['State_Abbreviation']]) #merge the two lists
all_stopwords <- tolower(all_stopwords) #make all state names/abbrevs lowercase
rm(stpwrds,addwords,states) 
  
  
  (f_weirdos <- content_transformer(function(x, pattern) gsub(pattern, "", x)))

#now do some special corpus cleaning...order of functions matters!
DroughtPlanProcessed <- DroughtPlanRaw %>%
  tm_map(f_weirdos,"[^[:alnum:] ]") %>% #gets rid of form feed (/f) and euro symbol, but not a accents
  tm_map(f_weirdos,"â") %>% #remove accents
  tm_map(content_transformer(tolower)) %>% #Switch to lower case
  tm_map(removeWords, all_stopwords) %>% #remove stopwords; want to remove stopwords 1st because they contain punctuation
  tm_map(removePunctuation) %>% #Remove punctuation marks 
  tm_map(removeNumbers) %>% #Remove numbers
  tm_map(stripWhitespace) #Remove white space 
  
  
```

###DataFrame

```{r}

DroughtPlanProcessed<- readRDS(file = "/Users/rachelmckane/Desktop/DroughtPlansProcessed_text.Rds")
DroughtPlanRaw<- readRDS( file = "/Users/rachelmckane/Desktop/DroughtPlansRaw_text.Rds")
WaterPlanProcessed<- readRDS(file = "/Users/rachelmckane/Desktop/WaterPlans_text.Rds")
WaterPlanRaw<- readRDS(file = "/Users/rachelmckane/Desktop/WaterPlansRaw_text.Rds")


writeCorpus(DroughtPlanProcessed, path = "/Users/RachelMckane/Desktop/Trash/DroughtPlanProcessed")
writeCorpus(DroughtPlanRaw, path = "/Users/RachelMckane/Desktop/Trash/DroughtPlanRaw")
writeCorpus(WaterPlanProcessed, path = "/Users/RachelMckane/Desktop/Trash/WaterPlanProcessed")
writeCorpus(WaterPlansRaw_text, path = "/Users/RachelMckane/Desktop/Trash/WaterPlanRaw")

AllPlans<- list.files("/Users/RachelMckane/Desktop/Trash", pattern = "\\.txt$",
                      recursive = TRUE, full.names = TRUE) 

Plan_Name <- AllPlans  %>% 
  str_replace(".txt", "") %>% 
  str_replace("/Users/RachelMckane/Desktop/Trash/", "") 

Plan_Texts <- AllPlans  %>% 
  map(read_file)

names(Plan_Texts) <- Plan_Name

DataFrame1 <- ldply(Plan_Texts, data.frame)  %>% 
  dplyr::rename(Id = .id, Plan_Text=X..i..) %>%
  dplyr:: mutate(Plan_Text = as.character(Plan_Text))

DataFrame2 <- DataFrame1 %>% separate(Id, into = c("Plan_Type", "State" ), sep = '[/]') %>%
  mutate(State = str_sub(State, 1, str_length(State)-4))

StateList<- read_csv("/Users/RachelMckane/Desktop/StatePlans.csv")

FinalDataFrame <- left_join(StateList, DataFrame2,  by=c("State" = "State", "Plan_Type" = "Plan_Type"))


saveRDS(FinalDataFrame, file = "/Users/rachelmckane/Desktop/FinalDataFrame.Rds")

  
```

